#define ARM_MODE_BIT_USR 0X10
#define ARM_MODE_BIT_FIQ 0X11
#define ARM_MODE_BIT_IRQ 0X12
#define ARM_MODE_BIT_SVC 0X13
#define ARM_MODE_BIT_ABT 0X17
#define ARM_MODE_BIT_UND 0X1B
#define ARM_MODE_BIT_SYS 0X1F
#define ARM_MODE_BIT_MON 0X16
